package com.pgp.app.appcomponents.database

object GolfClubData
{
   fun getClubs(): List<GolfClub> {
      return GolfClubData.clubsList
   }
     
   val clubsList: List<GolfClub> = listOf(
        GolfClub(1, "BUKIT JALIL GOLF & COUNTRY RESORT", "Kuala Lumpur"),
        GolfClub(2, "KELAB GOLF PERKHIDMATAN AWAM", "Kuala Lumpur"),
        GolfClub(3, "KELAB GOLF TITIWANGSA POLIS DIRAJA MALAYSIA", "Kuala Lumpur"),
        GolfClub(4, "KELAB REKREASI ANGKATAN TENTERA", "Negeri Sembilan"),
        GolfClub(5, "KUALA LUMPUR GOLF & COUNTRY CLUB", "Kuala Lumpur"),
        GolfClub(6, "THE ROYAL SELANGOR GOLF CLUB", "Selangor"),
        GolfClub(7, "AMVERTON COVE GOLF & ISLAND RESORT", "Selangor"),
        GolfClub(8, "BANGI GOLF RESORT", "Selangor"),
        GolfClub(9, "BUKIT BERUNTUNG GOLF & COUNTRY CLUB", "Selangor"),
        GolfClub(10, "BUKIT KEMUNING GOLF & COUNTRY RESORT", "Selangor"),
        GolfClub(11, "BUKIT UNGGUL COUNTRY CLUB", "Selangor"),
        GolfClub(12, "PERMAS JAYA GOLF CLUB", "Johor"),
        GolfClub(13, "DANAU GOLF CLUB", "Selangor"),
        GolfClub(14, "GLENMARIE GOLF & COUNTRY CLUB", "Selangor"),
        GolfClub(15, "SEGAMAT COUNTRY CLUB", "Johor"),
        GolfClub(16, "IMPIAN GOLF & COUNTRY CLUB", "Selangor"),
        GolfClub(17, "KELAB DARUL EHSAN", "Selangor"),
        GolfClub(18, "KELAB GOLF NEGARA SUBANG", "Selangor"),
        GolfClub(19, "KELAB GOLF SERI SELANGOR", "Selangor"),
        GolfClub(20, "UNIPUTRA GOLF CLUB", "Selangor"),
        GolfClub(21, "KELAB GOLF & COUNTRY KUALA KUBU BHARU", "Selangor"),
        GolfClub(22, "KELAB RAHMAN PUTRA MALAYSIA", "Selangor"),
        GolfClub(23, "KELAB REKREASI TENTERA UDARA (KRTU)", "Selangor"),
        GolfClub(24, "KELAB SRI MORIB", "Selangor"),
        GolfClub(25, "KINRARA GOLF CLUB", "Selangor"),
        GolfClub(26, "KOTA PERMAI GOLF & COUNTRY CLUB", "Selangor"),
        GolfClub(27, "LEMBAH BERINGIN GOLF CLUB", "Selangor"),
        GolfClub(28, "MONTEREZ GOLF & COUNTRY CLUB", "Selangor"),
        GolfClub(29, "PALM GARDEN GOLF CLUB", "Selangor"),
        GolfClub(30, "PORT KLANG GOLF RESORT", "Selangor"),
        GolfClub(31, "SAUJANA GOLF & COUNTRY CLUB", "Selangor"),
        GolfClub(32, "SULTAN ABDUL AZIZ SHAH GOLF & COUNTRY CLUB", "Selangor"),
        GolfClub(33, "SUNGAI LONG GOLF RESORT ", "Selangor"),
        GolfClub(34, "TASIK PUTERI GOLF & COUNTRY CLUB", "Selangor"),
        GolfClub(35, "TEMPLER PARK COUNTRY CLUB", "Selangor"),
        GolfClub(36, "THE MINES RESORT & GOLF CLUB", "Selangor"),
        GolfClub(37, "THE ROYAL KAMPUNG KUANTAN CLUB", "Selangor"),
        GolfClub(38, "TROPICANA GOLF COUNTRY RESORT", "Selangor"),
        GolfClub(39, "VALENCIA CLUB & VILLAGE SQUARE", "Selangor"),
        GolfClub(40, "LABUAN GOLF CLUB", "Labuan"),
        GolfClub(41, "LABUAN INTERNATIONAL GOLF CLUB", "Labuan"),
        GolfClub(42, "DAMAI GOLF & COUNTRY CLUB", "Sarawak"),
        GolfClub(43, "EASTWOOD VALLEY GOLF & COUNTRY CLUB", "Sarawak"),
        GolfClub(44, "KELAB GOLF BINTULU", "Sarawak"),
        GolfClub(45, "KELAB GOLF MIRI", "Sarawak"),
        GolfClub(46, "KELAB GOLF SARAWAK", "Sarawak"),
        GolfClub(47, "KELAB GOLF SIBU", "Sarawak"),
        GolfClub(48, "SAMARAHAN COUNTRY CLUB", "Sarawak"),
        GolfClub(49, "BORNEO GOLF & COUNTRY CLUB", "Sabah"),
        GolfClub(50, "DALIT BAY GOLF CLUB & SPA", "Sabah"),
        GolfClub(51, "KENINGAU GOLF & COUNTRY CLUB", "Sabah"),
        GolfClub(52, "KUDAT GOLF CLUB", "Sabah"),
        GolfClub(53, "LAHAD DATU GOLF & COUNTRY CLUB", "Sabah"),
        GolfClub(54, "MOUNT KINABALU GOLF CLUB", "Sabah"),
        GolfClub(55, "NEXUS GOLF RESORT KARAMBUNAI", "Sabah"),
        GolfClub(56, "RANAU GOLF CLUB", "Sabah"),
        GolfClub(57, "SABAH GOLF & COUNTRY CLUB", "Sabah"),
        GolfClub(58, "SANDAKAN GOLF & COUNTRY CLUB", "Sabah"),
        GolfClub(59, "SHAN – SHUI GOLF & COUNTRY RESORT", "Sabah"),
        GolfClub(60, "SIGALONG GOLF & COUNTRY CLUB", "Sabah"),
        GolfClub(61, "SUTERA HARBOUR GOLF & COUNTRY CLUB", "Sabah"),
        GolfClub(62, "TAMBUNAN GOLF CLUB", "Sabah"),
        GolfClub(63, "TAWAU GOLF CLUB", "Sabah"),
        GolfClub(64, "THE KINABALU GOLF CLUB", "Sabah"),
        GolfClub(65, "GREEN ACRES GOLF & COUNTRY RESORT", "Terengganu"),
        GolfClub(66, "KELAB GOLF DESA DUNGUN", "Terengganu"),
        GolfClub(67, "KELAB GOLF DIRAJA TERENGGANU", "Terengganu"),
        GolfClub(68, "KELAB GOLF & REKREASI PETRONAS", "Terengganu"),
        GolfClub(69, "KUALA TERENGGANU GOLF RESORT", "Terengganu"),
        GolfClub(70, "RESORT WORLD KIJAL", "Terengganu"),
        GolfClub(71, "KELAB GOLF PUTRA", "Perlis"),
        GolfClub(72, "CLEARWATER SANCTUARY GOLF RESORT", "Perak"),
        GolfClub(73, "DAMAI LAUT GOLF & COUNTRY CLUB", "Perak"),
        GolfClub(74, "KELAB GOLF BRIDGED UTARA", "Perak"),
        GolfClub(75, "KELAB GOLF KINTA", "Perak"),
        GolfClub(76, "KELAB GOLF KUALA KANGSAR", "Perak"),
        GolfClub(77, "SEBANA GOLF & MARINA RESORT", "Johor"),
        GolfClub(78, "MERU VALLEY GOLF & COUNTRY CLUB", "Perak"),
        GolfClub(79, "ROYAL PERAK GOLF CLUB", "Perak"),
        GolfClub(80, "PONDEROSA GOLF & COUNTRY CLUB", "Johor"),
        GolfClub(81, "TELUK INTAN GOLF & COUNTRY CLUB", "Perak"),
        GolfClub(82, "AWANA GENTING GOLF & COUNTRY RESORT", "Pahang"),
        GolfClub(83, "BERJAYA HILLS GOLF & COUNTRY CLUB", "Pahang"),
        GolfClub(84, "KELAB GOLF BENTONG", "Pahang"),
        GolfClub(85, "KELAB GOLF DIRAJA PEKAN", "Pahang"),
        GolfClub(86, "KELAB GOLF SULTAN AHMAD SHAH (SAS) CAMERON HIGHLANDS", "Pahang"),
        GolfClub(87, "KELAB REKREASI INDERA KUANTAN", "Pahang"),
        GolfClub(88, "KELAB REKREASI SRI MAHKOTA", "Pahang"),
        GolfClub(89, "KELAB REKREASI TUDM KUANTAN (KRTK)", "Pahang"),
        GolfClub(90, "MAHKOTA GOLF & COUNTRY CLUB", "Pahang"),
        GolfClub(91, "MARAN HILL GOLF RESORT", "Pahang"),
        GolfClub(92, "ROYAL PAHANG GOLF CLUB", "Pahang"),
        GolfClub(93, "BUKIT JAWI GOLF RESORT", "Pulau Pinang"),
        GolfClub(94, "KELAB REKREASI TENTERA UDARA BUTTERWORTH", "Pulau Pinang"),
        GolfClub(95, "PENANG GOLF CLUB (BUKIT JAMBUL CC)", "Pulau Pinang"),
        GolfClub(96, "PENANG GOLF RESORT", "Pulau Pinang"),
        GolfClub(97, "PENANG TURF CLUB GOLF SECTION", "Pulau Pinang"),
        GolfClub(98, "ORCHARD GOLF & COUNTRY RESORT", "Johor"),
        GolfClub(99, "NILAI SPRINGS GOLF & COUNTRY CLUB", "Negeri Sembilan"),
        GolfClub(100, "PORT DICKSON GOLF & COUNTRY CLUB", "Negeri Sembilan"),
        GolfClub(101, "ROYAL SRI MENANTI GOLF & COUNRTY CLUB", "Negeri Sembilan"),
        GolfClub(102, "SEREMBAN INTERNATIONAL GOLF CLUB", "Negeri Sembilan"),
        GolfClub(103, "STAFFIELD COUNTRY RESORT", "Negeri Sembilan"),
        GolfClub(104, "CINTA SAYANG GOLF & COUNTRY RESORT", "Kedah"),
        GolfClub(105, "DARULAMAN GOLF & COUNTRY CLUB", "Kedah"),
        GolfClub(106, "GUNUNG RAYA GOLF RESORT", "Kedah"),
        GolfClub(107, "HARVARD GOLF & COUNTRY CLUB", "Kedah"),
        GolfClub(108, "KELAB KEDAH DARULAMAN DIRAJA", "Kedah"),
        GolfClub(109, "KELAB REKREASI UNIVERSITI UTARA MALAYSIA", "Kedah"),
        GolfClub(110, "KELAB SUNGAI PETANI", "Kedah"),
        GolfClub(111, "KULIM GOLF & COUNTRY RESORT", "Kedah"),
        GolfClub(112, "THE ELS CLUB MALAYSIA", "Kedah"),
        GolfClub(113, "PERMAIPURA GOLF & COUNTRY CLUB", "Kedah"),
        GolfClub(114, "KELAB GOLF GUA MUSANG", "Kelantan"),
        GolfClub(115, "KUKUP GOLF RESORT", "Johor"),
        GolfClub(116, "KELANTAN GOLF & COUNTRY CLUB", "Kelantan"),
        GolfClub(117, "AYER KEROH COUNTRY CLUB", "Melaka"),
        GolfClub(118, "A'FAMOSA GOLF RESORT", "Melaka"),
        GolfClub(119, "ORNA GOLF & COUNTRY CLUB", "Melaka"),
        GolfClub(120, "TIARA MELAKA GOLF & COUNTRY CLUB", "Melaka"),
        GolfClub(121, "AUSTIN HEIGHTS GOLF & COUNTRY RESORT", "Johor"),
        GolfClub(122, "BUKIT BANANG GOLF & COUNTRY CLUB", "Johor"),
        GolfClub(123, "DAIMAN 18 JOHOR BAHRU", "Johor"),
        GolfClub(124, "HORIZON HILLS GOLF & COUNTRY CLUB", "Johor"),
        GolfClub(125, "JOHOR GOLF & COUNTRY CLUB", "Johor"),
        GolfClub(126, "KELAB GOLF BATU PAHAT", "Johor"),
        GolfClub(127, "KELAB GOLF TANJONG EMAS", "Johor"),
        GolfClub(128, "KLUANG GOLF CLUB", "Johor"),
        GolfClub(129, "PALM RESORT GOLF & COUNTRY CLUB", "Johor"),
        GolfClub(130, "PALM VILLA GOLF & COUNTRY RESORT", "Johor"),
        GolfClub(131, "STARHILL GOLF & COUNTRY CLUB", "Johor"),
        GolfClub(132, "TANJONG PUTERI GOLF RESORT", "Johor"),
        GolfClub(133, "THE LEGENDS GOLF & COUNTRY RESORT", "Johor")
    )}
