package com.pgp.app.appcomponents.database

object GolfClubData
{
   fun getClubs(): List<GolfClub> {
      return GolfClubData.clubsList
   }
     
   val clubsList: List<GolfClub> = listOf(
        GolfClub(name = "BUKIT JALIL GOLF & COUNTRY RESORT", location = "Kuala Lumpur"),
        GolfClub(name = "KELAB GOLF PERKHIDMATAN AWAM", location = "Kuala Lumpur"),
        GolfClub(name = "KELAB GOLF TITIWANGSA POLIS DIRAJA MALAYSIA", location = "Kuala Lumpur"),
        GolfClub(name = "KELAB REKREASI ANGKATAN TENTERA", location = "Negeri Sembilan"),
        GolfClub(name = "KUALA LUMPUR GOLF & COUNTRY CLUB", location = "Kuala Lumpur"),
        GolfClub(name = "THE ROYAL SELANGOR GOLF CLUB", location = "Selangor"),
        GolfClub(name = "AMVERTON COVE GOLF & ISLAND RESORT", location = "Selangor"),
        GolfClub(name = "BANGI GOLF RESORT", location = "Selangor"),
        GolfClub(name = "BUKIT BERUNTUNG GOLF & COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "BUKIT KEMUNING GOLF & COUNTRY RESORT", location = "Selangor"),
        GolfClub(name = "BUKIT UNGGUL COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "PERMAS JAYA GOLF CLUB", location = "Johor"),
        GolfClub(name = "DANAU GOLF CLUB", location = "Selangor"),
        GolfClub(name = "GLENMARIE GOLF & COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "SEGAMAT COUNTRY CLUB", location = "Johor"),
        GolfClub(name = "IMPIAN GOLF & COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "KELAB DARUL EHSAN", location = "Selangor"),
        GolfClub(name = "KELAB GOLF NEGARA SUBANG", location = "Selangor"),
        GolfClub(name = "KELAB GOLF SERI SELANGOR", location = "Selangor"),
        GolfClub(name = "UNIPUTRA GOLF CLUB", location = "Selangor"),
        GolfClub(name = "KELAB GOLF & COUNTRY KUALA KUBU BHARU", location = "Selangor"),
        GolfClub(name = "KELAB RAHMAN PUTRA MALAYSIA", location = "Selangor"),
        GolfClub(name = "KELAB REKREASI TENTERA UDARA (KRTU)", location = "Selangor"),
        GolfClub(name = "KELAB SRI MORIB", location = "Selangor"),
        GolfClub(name = "KINRARA GOLF CLUB", location = "Selangor"),
        GolfClub(name = "KOTA PERMAI GOLF & COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "LEMBAH BERINGIN GOLF CLUB", location = "Selangor"),
        GolfClub(name = "MONTEREZ GOLF & COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "PALM GARDEN GOLF CLUB", location = "Selangor"),
        GolfClub(name = "PORT KLANG GOLF RESORT", location = "Selangor"),
        GolfClub(name = "SAUJANA GOLF & COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "SULTAN ABDUL AZIZ SHAH GOLF & COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "SUNGAI LONG GOLF RESORT ", location = "Selangor"),
        GolfClub(name = "TASIK PUTERI GOLF & COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "TEMPLER PARK COUNTRY CLUB", location = "Selangor"),
        GolfClub(name = "THE MINES RESORT & GOLF CLUB", location = "Selangor"),
        GolfClub(name = "THE ROYAL KAMPUNG KUANTAN CLUB", location = "Selangor"),
        GolfClub(name = "TROPICANA GOLF COUNTRY RESORT", location = "Selangor"),
        GolfClub(name = "VALENCIA CLUB & VILLAGE SQUARE", location = "Selangor"),
        GolfClub(name = "LABUAN GOLF CLUB", location = "Labuan"),
        GolfClub(name = "LABUAN INTERNATIONAL GOLF CLUB", location = "Labuan"),
        GolfClub(name = "DAMAI GOLF & COUNTRY CLUB", location = "Sarawak"),
        GolfClub(name = "EASTWOOD VALLEY GOLF & COUNTRY CLUB", location = "Sarawak"),
        GolfClub(name = "KELAB GOLF BINTULU", location = "Sarawak"),
        GolfClub(name = "KELAB GOLF MIRI", location = "Sarawak"),
        GolfClub(name = "KELAB GOLF SARAWAK", location = "Sarawak"),
        GolfClub(name = "KELAB GOLF SIBU", location = "Sarawak"),
        GolfClub(name = "SAMARAHAN COUNTRY CLUB", location = "Sarawak"),
        GolfClub(name = "BORNEO GOLF & COUNTRY CLUB", location = "Sabah"),
        GolfClub(name = "DALIT BAY GOLF CLUB & SPA", location = "Sabah"),
        GolfClub(name = "KENINGAU GOLF & COUNTRY CLUB", location = "Sabah"),
        GolfClub(name = "KUDAT GOLF CLUB", location = "Sabah"),
        GolfClub(name = "LAHAD DATU GOLF & COUNTRY CLUB", location = "Sabah"),
        GolfClub(name = "MOUNT KINABALU GOLF CLUB", location = "Sabah"),
        GolfClub(name = "NEXUS GOLF RESORT KARAMBUNAI", location = "Sabah"),
        GolfClub(name = "RANAU GOLF CLUB", location = "Sabah"),
        GolfClub(name = "SABAH GOLF & COUNTRY CLUB", location = "Sabah"),
        GolfClub(name = "SANDAKAN GOLF & COUNTRY CLUB", location = "Sabah"),
        GolfClub(name = "SHAN – SHUI GOLF & COUNTRY RESORT", location = "Sabah"),
        GolfClub(name = "SIGALONG GOLF & COUNTRY CLUB", location = "Sabah"),
        GolfClub(name = "SUTERA HARBOUR GOLF & COUNTRY CLUB", location = "Sabah"),
        GolfClub(name = "TAMBUNAN GOLF CLUB", location = "Sabah"),
        GolfClub(name = "TAWAU GOLF CLUB", location = "Sabah"),
        GolfClub(name = "THE KINABALU GOLF CLUB", location = "Sabah"),
        GolfClub(name = "GREEN ACRES GOLF & COUNTRY RESORT", location = "Terengganu"),
        GolfClub(name = "KELAB GOLF DESA DUNGUN", location = "Terengganu"),
        GolfClub(name = "KELAB GOLF DIRAJA TERENGGANU", location = "Terengganu"),
        GolfClub(name = "KELAB GOLF & REKREASI PETRONAS", location = "Terengganu"),
        GolfClub(name = "KUALA TERENGGANU GOLF RESORT", location = "Terengganu"),
        GolfClub(name = "RESORT WORLD KIJAL", location = "Terengganu"),
        GolfClub(name = "KELAB GOLF PUTRA", location = "Perlis"),
        GolfClub(name = "CLEARWATER SANCTUARY GOLF RESORT", location = "Perak"),
        GolfClub(name = "DAMAI LAUT GOLF & COUNTRY CLUB", location = "Perak"),
        GolfClub(name = "KELAB GOLF BRIDGED UTARA", location = "Perak"),
        GolfClub(name = "KELAB GOLF KINTA", location = "Perak"),
        GolfClub(name = "KELAB GOLF KUALA KANGSAR", location = "Perak"),
        GolfClub(name = "SEBANA GOLF & MARINA RESORT", location = "Johor"),
        GolfClub(name = "MERU VALLEY GOLF & COUNTRY CLUB", location = "Perak"),
        GolfClub(name = "ROYAL PERAK GOLF CLUB", location = "Perak"),
        GolfClub(name = "PONDEROSA GOLF & COUNTRY CLUB", location = "Johor"),
        GolfClub(name = "TELUK INTAN GOLF & COUNTRY CLUB", location = "Perak"),
        GolfClub(name = "AWANA GENTING GOLF & COUNTRY RESORT", location = "Pahang"),
        GolfClub(name = "BERJAYA HILLS GOLF & COUNTRY CLUB", location = "Pahang"),
        GolfClub(name = "KELAB GOLF BENTONG", location = "Pahang"),
        GolfClub(name = "KELAB GOLF DIRAJA PEKAN", location = "Pahang"),
        GolfClub(name = "KELAB GOLF SULTAN AHMAD SHAH (SAS) CAMERON HIGHLANDS", location = "Pahang"),
        GolfClub(name = "KELAB REKREASI INDERA KUANTAN", location = "Pahang"),
        GolfClub(name = "KELAB REKREASI SRI MAHKOTA", location = "Pahang"),
        GolfClub(name = "KELAB REKREASI TUDM KUANTAN (KRTK)", location = "Pahang"),
        GolfClub(name = "MAHKOTA GOLF & COUNTRY CLUB", location = "Pahang"),
        GolfClub(name = "MARAN HILL GOLF RESORT", location = "Pahang"),
        GolfClub(name = "ROYAL PAHANG GOLF CLUB", location = "Pahang"),
        GolfClub(name = "BUKIT JAWI GOLF RESORT", location = "Pulau Pinang"),
        GolfClub(name = "KELAB REKREASI TENTERA UDARA BUTTERWORTH", location = "Pulau Pinang"),
        GolfClub(name = "PENANG GOLF CLUB (BUKIT JAMBUL CC)", location = "Pulau Pinang"),
        GolfClub(name = "PENANG GOLF RESORT", location = "Pulau Pinang"),
        GolfClub(name = "PENANG TURF CLUB GOLF SECTION", location = "Pulau Pinang"),
        GolfClub(name = "ORCHARD GOLF & COUNTRY RESORT", location = "Johor"),
        GolfClub(name = "NILAI SPRINGS GOLF & COUNTRY CLUB", location = "Negeri Sembilan"),
        GolfClub(name = "PORT DICKSON GOLF & COUNTRY CLUB", location = "Negeri Sembilan"),
        GolfClub(name = "ROYAL SRI MENANTI GOLF & COUNRTY CLUB", location = "Negeri Sembilan"),
        GolfClub(name = "SEREMBAN INTERNATIONAL GOLF CLUB", location = "Negeri Sembilan"),
        GolfClub(name = "STAFFIELD COUNTRY RESORT", location = "Negeri Sembilan"),
        GolfClub(name = "CINTA SAYANG GOLF & COUNTRY RESORT", location = "Kedah"),
        GolfClub(name = "DARULAMAN GOLF & COUNTRY CLUB", location = "Kedah"),
        GolfClub(name = "GUNUNG RAYA GOLF RESORT", location = "Kedah"),
        GolfClub(name = "HARVARD GOLF & COUNTRY CLUB", location = "Kedah"),
        GolfClub(name = "KELAB KEDAH DARULAMAN DIRAJA", location = "Kedah"),
        GolfClub(name = "KELAB REKREASI UNIVERSITI UTARA MALAYSIA", location = "Kedah"),
        GolfClub(name = "KELAB SUNGAI PETANI", location = "Kedah"),
        GolfClub(name = "KULIM GOLF & COUNTRY RESORT", location = "Kedah"),
        GolfClub(name = "THE ELS CLUB MALAYSIA", location = "Kedah"),
        GolfClub(name = "PERMAIPURA GOLF & COUNTRY CLUB", location = "Kedah"),
        GolfClub(name = "KELAB GOLF GUA MUSANG", location = "Kelantan"),
        GolfClub(name = "KUKUP GOLF RESORT", location = "Johor"),
        GolfClub(name = "KELANTAN GOLF & COUNTRY CLUB", location = "Kelantan"),
        GolfClub(name = "AYER KEROH COUNTRY CLUB", location = "Melaka"),
        GolfClub(name = "A'FAMOSA GOLF RESORT", location = "Melaka"),
        GolfClub(name = "ORNA GOLF & COUNTRY CLUB", location = "Melaka"),
        GolfClub(name = "TIARA MELAKA GOLF & COUNTRY CLUB", location = "Melaka"),
        GolfClub(name = "AUSTIN HEIGHTS GOLF & COUNTRY RESORT", location = "Johor"),
        GolfClub(name = "BUKIT BANANG GOLF & COUNTRY CLUB", location = "Johor"),
        GolfClub(name = "DAIMAN 18 JOHOR BAHRU", location = "Johor"),
        GolfClub(name = "HORIZON HILLS GOLF & COUNTRY CLUB", location = "Johor"),
        GolfClub(name = "JOHOR GOLF & COUNTRY CLUB", location = "Johor"),
        GolfClub(name = "KELAB GOLF BATU PAHAT", location = "Johor"),
        GolfClub(name = "KELAB GOLF TANJONG EMAS", location = "Johor"),
        GolfClub(name = "KLUANG GOLF CLUB", location = "Johor"),
        GolfClub(name = "PALM RESORT GOLF & COUNTRY CLUB", location = "Johor"),
        GolfClub(name = "PALM VILLA GOLF & COUNTRY RESORT", location = "Johor"),
        GolfClub(name = "STARHILL GOLF & COUNTRY CLUB", location = "Johor"),
        GolfClub(name = "TANJONG PUTERI GOLF RESORT", location = "Johor"),
        GolfClub(name = "THE LEGENDS GOLF & COUNTRY RESORT", location = "Johor")
    )}
